### ISSUE TITLE
[Feature request] Tags filter

### ISSUE THREAD

**Issue by MarceauKa** [spatie/nova-tags-field#18]
It could be nice to have this feature

Actually It works with the search functionnality and this nova package: https://novapackages.com/packages/titasgailius/search-relations

**Comment by freekmurze** [comment]
Feel free to PR features. If the code is simple enough, I'll consider merging it in.

**Comment by olivM** [comment]
i created a dedicated filter package for spatie/laravel-tags : https://github.com/Mahi-Mahi/SpatieTagsNovaFilter

but i don't know if packaging both the custom field and custom filter in the same package is the right choice

**Comment by Lednerb** [comment]
Nova 4 now contains the `filterable` method for many fields by default.

It would be nice to integrate the filterable function directly in this package. because the https://github.com/Mahi-Mahi/SpatieTagsNovaFilter does not support Nova 4 at the moment?

@olivM what do you think about it regarding support in Nova v4?
