### ISSUE TITLE
Not saving Tags with type

### ISSUE THREAD

**Issue by u12206050** [spatie/nova-tags-field#80]
I have a `Post` model that contains the `HasTags` Trait, and in my Nova Resource for `Post` my fields are: 
```
            Tags::make(__('Topics'))->type('topic'),
            Tags::make(__('Tags'))
```
I am able to create and save `Tags` to a post but not `Topics` which is tags with type `topic`

Am I missing anything, couldn't find any documentation on any extra steps I need to get types to work.

**Comment by mattlibera** [comment]
@u12206050 I had something similar with tags not saving... and then realized I was overriding the polymorphic relationship that the package provides (e.g. `taggables`). Turns out I had put a `json` column called `tags` in my model. Once I removed that, everything was good for me.

Any chance that helps you?

**Comment by ashestree87** [comment]
@u12206050 did you manage to work this out? having the same problem.

**Comment by u12206050** [comment]
No unfortunately not, my model didn't have `tags` column. In the end I gave up and just used SelectPlus

**Comment by LorenzoSapora** [comment]
I just hit this issue, too. And yes, it was because I had a `public function tags(){}` in my model. So any future issue-divers, check that.
