### ISSUE TITLE
Laravel sanctum and nova-tags-field

### ISSUE THREAD

**Issue by IMPMAC** [spatie/nova-tags-field#87]
Hi. 
Not sure if the issue is within this package or Laravel sanctum.

But if you were to utilize Laravel Sanctum package to authenticate an SPA using the kernel adjustment `EnsureFrontendRequestsAreStateful` in the `app/Http/Kernel.php`

When you search for tags, it will result in a 401 unauthenticated response and you being logged out immediately.

**Comment by martinzuro** [comment]
I'm finding the same issue here.

**Comment by felly** [comment]
I think this happens because of the 'api' middleware in `TagsFieldServiceProvider.php`.

My current workaround is to add this package to the 'dont-discover' part of composer.json:
```json
"extra": {
    "laravel": {
        "dont-discover": [
            "spatie/nova-tags-field"
        ]
    }
},
```

Then extending the service provider and skip the api middleware:
```php
class TagsFieldServiceProvider extends \Spatie\TagsField\TagsFieldServiceProvider
{
    protected function routes()
    {
        if ($this->app->routesAreCached()) {
            return;
        }

        Route::middleware(['nova', Authorize::class])
            ->prefix('nova-vendor/spatie/nova-tags-field')
            ->group(base_path().'/vendor/spatie/nova-tags-field/routes/api.php');
    }
}
```

And manually adding this service provider to `config/app.php`.

If anybody knows a better solution, I'll be glad to hear it!

**Comment by aliwesome** [comment]
is there any better solution for this? I'm facing the same issue.
